routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Auth::routes();

Route::get('/home', 'HomeController@index');

Route::resource('notifies', 'notifyController');

Route::resource('entities', 'entityController');

Route::resource('atributes', 'atributeController');

Route::resource('$iotServices', '$iotServiceController');

Route::resource('iotServices', 'iotServiceController');

Route::resource('iotDevices', 'iot_deviceController');

Route::resource('iotDeviceAttributes', 'iot_device_attributeController');

Route::resource('iotDeviceAttributes', 'iot_device_attributeController');

Route::get('fitbits/sync', 'fitbitController@syncup')->name('fitbits.sync');

Route::get('fitbits/sync/sleep', 'fitbitController@syncupSleep')->name('fitbits.syncupSleep');

Route::resource('fitbits', 'fitbitController');

Route::get('temperatura/form', 'fiwareController@form')->name('temperatura.form');

Route::get('temperatura/sensores/{nombre}', 'fiwareController@getSensores');

Route::post('temperatura/consulta', 'fiwareController@consulta')->name('temperatura.consulta');

Route::get('presion/form', 'fiwareController@formPresion')->name('presion.formPresion');

Route::get('presion/sensores/{nombre}', 'fiwareController@getSensoresPresion');

Route::post('presion/consulta', 'fiwareController@consultaPresion')->name('presion.consultaPresion');

Route::get('humedad/form', 'fiwareController@formHumedad')->name('humedad.formHumedad');

Route::get('humedad/sensores/{nombre}', 'fiwareController@getSensoresHumedad');

Route::post('humedad/consulta', 'fiwareController@consultaHumedad')->name('humedad.consultaHumedad');

Route::resource('temperatura', 'fiwareController');

//Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

Route::resource('heartRates', 'heartRateController');

Route::resource('heartInterDays', 'heartInterDayController');

Route::resource('sleeps', 'sleepController');

Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

app/Models/iot_device.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class iot_device
 * @package App\Models
 * @version June 2, 2019, 2:31 pm UTC
 *
 * @property string ipServer
 * @property string fiwareService
 * @property string fiwarePath
 * @property string device_id
 * @property string entity_name
 * @property string entity_type
 */
class iot_device extends Model
{
    use SoftDeletes;

    public $table = 'iot_devices';


    protected $dates = ['deleted_at'];


    public $fillable = [
        'ipServer',
        'fiwareService',
        'fiwarePath',
        'device_id',
        'entity_name',
        'entity_type'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'ipServer' => 'string',
        'fiwareService' => 'string',
        'fiwarePath' => 'string',
        'device_id' => 'string',
        'entity_name' => 'string',
        'entity_type' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'fiwarePath' => 'required',
        'device_id' => 'required',
        'entity_type' => 'required'
    ];

    public function atributoIOT()

    {

        return $this->hasMany('App\Models\iot_device_attribute');

    }




}

app/Http/Controllers/iot_deviceController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Createiot_deviceRequest;
use App\Http\Requests\Updateiot_deviceRequest;
use App\Repositories\iot_deviceRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;
use App\Models\iot_device_attribute;
use Log;
use App\Models\iotService;
use App\Models\iot_device;
use App\Models\fitbit;
use Illuminate\Support\Facades\DB;

class iot_deviceController extends AppBaseController
{
    /** @var  iot_deviceRepository */
    private $iotDeviceRepository;

    public function __construct(iot_deviceRepository $iotDeviceRepo)
    {
        $this->iotDeviceRepository = $iotDeviceRepo;
    }

    /**
     * Display a listing of the iot_device.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $iotDevices = $this->iotDeviceRepository->all();

        return view('iot_devices.index')
            ->with('iotDevices', $iotDevices);
    }

    /**
     * Show the form for creating a new iot_device.
     *
     * @return Response
     */
    public function create()
    {
        $userId = fitbit::pluck('name','user_id');
        $conjunto = iotService::pluck('entity_type','entity_type');
        $spa = iotService::pluck('fiwarePath','fiwarePath');
        return view('iot_devices.create')->with('conjunto', $conjunto)->with('spa',$spa)->with('userId',$userId);
    }

    /**
     * Store a newly created iot_device in storage.
     *
     * @param Createiot_deviceRequest $request
     *
     * @return Response
     */
    public function store(Createiot_deviceRequest $request)
    {

        $input = $request->all();

        /***validar ip server  */
        try{

            /*proceso para crear entidada en mongo*/
            $fiwareService = config('fiware.fiware_service');
            $fiwarePath = $input['fiwarePath'];
            $ip = config('fiware.fiware_servidor_ip');
            $iotPort = config('fiware.fiware_iot_port');
            $url = "http://$ip:$iotPort/iot/devices";
            $deviceId = $input['device_id'];
            //$entityName = $input['entity_name'];
            $entityType = ucfirst($input['entity_type']);

            /*creacion de identidad*/

            $data['devices'][0]['device_id'] = strtolower($entityType).$deviceId;
            //$data['devices'][0]['entity_name'] = 'urn:ngsi-Id:'.ucfirst($entityType).':'.$deviceId;
            //$data['devices'][0]['entity_name'] = 'urn:ngsi-Id:'.ucfirst($entityType);
            $data['devices'][0]['entity_name'] = $deviceId;
            $data['devices'][0]['entity_type'] = ucfirst($entityType);
            $data['devices'][0]['timezone'] = config('fiware.fiware_timezone');

            $idA = iotService::where('entity_type','=',$entityType)->get('id')->toArray();
            $attr = iot_device_attribute::where('attr_id','=',$idA[0]['id'])->get()->toArray();

            $i=0;
            foreach($attr as $clave => $valor){
                $data['devices'][0]['attributes'][$i]['object_id'] =$valor['objective'];
                $data['devices'][0]['attributes'][$i]['name'] =$valor['name'];
                $data['devices'][0]['attributes'][$i]['type'] = $valor['type'];
                $field = $valor['name'];
                $i++;
            }

            $data['devices'][0]['static_attributes'][0]['name'] = "user_id";
            $data['devices'][0]['static_attributes'][0]['type'] = "Relationship";
            $data['devices'][0]['static_attributes'][0]['value'] = $deviceId;
            $data['devices'][0]['static_attributes'][1]['name'] = "continent";
            $data['devices'][0]['static_attributes'][1]['type'] = "Relationship";
            $data['devices'][0]['static_attributes'][1]['value'] = config('fiware.fiware_continent');
            $data['devices'][0]['static_attributes'][2]['name'] = "country";
            $data['devices'][0]['static_attributes'][2]['type'] = "Relationship";
            $data['devices'][0]['static_attributes'][2]['value'] = config('fiware.fiware_country');
            $data['devices'][0]['static_attributes'][3]['name'] = "city";
            $data['devices'][0]['static_attributes'][3]['type'] = "Relationship";
            $data['devices'][0]['static_attributes'][3]['value'] = config('fiware.fiware_city');
            $data['devices'][0]['static_attributes'][4]['name'] = "dock";
            $data['devices'][0]['static_attributes'][4]['type'] = "Relationship";
            $data['devices'][0]['static_attributes'][4]['value'] = config('fiware.fiware_dock');

            $data_json = json_encode($data);
            /***********AGREGAR CAMPOS DE ATIBUTOS  ATABLA********/
             /*$arrayAttrEst = $data['devices'][0]['static_attributes'];
           foreach($arrayAttrEst as $campo => $valor){
                $field = $valor['name'];
                $cadenaSql = "ALTER TABLE $entityType ADD $field varchar(191) NULL";
                DB::statement($cadenaSql);
            }*/








            /***************************************************** */
            /************fin */
            $headers = [
                "Content-Type:application/json",
                "fiware-service:$fiwareService" ,
                "fiware-servicepath:$fiwarePath",
            ];

            $ch = curl_init();
            curl_setopt($ch, CURLOPT_URL, $url);
            curl_setopt($ch, CURLOPT_POST, 1);
            curl_setopt($ch, CURLOPT_POSTFIELDS,$data_json);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
            curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
            $server_output = curl_exec ($ch);

            if($server_output === false)
            {
                Flash::error('Error Number:'.curl_errno($ch).',Error String:'.curl_error($ch) );
                curl_close ($ch);
                return redirect(route('iotDevices.create'))->withInput();
            }
            curl_close ($ch);

            $respuesta = json_decode($server_output);



            if(isset($respuesta->name)){


                Flash::error('Error:'.$respuesta->name.','.$respuesta->message);

                return redirect(route('iotDevices.create'))->withInput();

            }
        }

        catch(\Exception $e){
            Log::critical('No se pudo crear iot device: ' . $e->getCode() . ', ' . $e->getLine() . ', ' . $e->getMessage());
            return response('No se pudo crear iot device: ' . $e->getCode() . ', ' . $e->getLine() . ', ' . $e->getMessage(), 500);
        }
        $input['device_id'] = $entityType.$deviceId;
        $input['entity_name'] = 'urn:ngsis-Id:'.$entityType;

        $iotDevice = new iot_device;
        $iotDevice->ipServer = $ip;
        $iotDevice->fiwareService = $fiwareService;
        $iotDevice->fiwarePath = $fiwarePath;
        $iotDevice->device_id = strtolower($entityType).$deviceId;
        $iotDevice->entity_name = 'urn:ngsi-Id:'.ucfirst($entityType);
        $iotDevice->entity_type = $entityType;
        $iotDevice->save();


        //$iotDevice = $this->iotDeviceRepository->create($input);
        /*$iotDevice = $this->iotDeviceRepository->find($iotDevice->id);

        $attrName = $input['attrName'];
        $attrType = $input['attrType'];
        $attr = new iot_device_attribute;
        $i = 0;
        foreach ($attrName as $name) {
            $attr->name = $name;
            $attr->type = $attrType[$i];

            $iotDevice->atributoIOT()->save($attr);
            $i++;
            $attr = new iot_device_attribute;

        }*/

        Flash::success('Iot Device saved successfully.');

        return redirect(route('iotDevices.index'));
    }

    /**
     * Display the specified iot_device.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $iotDevice = $this->iotDeviceRepository->find($id);

        if (empty($iotDevice)) {
            Flash::error('Iot Device not found');

            return redirect(route('iotDevices.index'));
        }

        return view('iot_devices.show')->with('iotDevice', $iotDevice);
    }

    /**
     * Show the form for editing the specified iot_device.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $iotDevice = $this->iotDeviceRepository->find($id);

        if (empty($iotDevice)) {
            Flash::error('Iot Device not found');

            return redirect(route('iotDevices.index'));
        }

        return view('iot_devices.edit')->with('iotDevice', $iotDevice);
    }

    /**
     * Update the specified iot_device in storage.
     *
     * @param int $id
     * @param Updateiot_deviceRequest $request
     *
     * @return Response
     */
    public function update($id, Updateiot_deviceRequest $request)
    {
        $iotDevice = $this->iotDeviceRepository->find($id);

        if (empty($iotDevice)) {
            Flash::error('Iot Device not found');

            return redirect(route('iotDevices.index'));
        }

        $iotDevice = $this->iotDeviceRepository->update($request->all(), $id);

        Flash::success('Iot Device updated successfully.');

        return redirect(route('iotDevices.index'));
    }

    /**
     * Remove the specified iot_device from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $iotDevice = $this->iotDeviceRepository->find($id);



        if (empty($iotDevice)) {
            Flash::error('Iot Device not found');

            return redirect(route('iotDevices.index'));
        }

        /****************CURL */

        $fiwareService = $iotDevice->fiwareService;
        $fiwarePath = $iotDevice->fiwarePath;
        $ip = $iotDevice->ipServer;
        $iotPort = config('fiware.fiware_iot_port');
        $url = "http://$ip:$iotPort/iot/devices/$iotDevice->device_id";

resources/views/iot_devices/create.blade.php
@extends('layouts.app')

@section('content')
<section class="content-header flexInput">
        <div class="headerInput vCenter">
            <h1>Dar de Alta</h1>
        </div>

    <div class="content">
        @include('adminlte-templates::common.errors')
        @include('flash::message')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row formInput">
                    {!! Form::open(['route' => 'iotDevices.store']) !!}

                        @include('iot_devices.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/iot_devices/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Iot Dispositivo
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($iotDevice, ['route' => ['iotDevices.update', $iotDevice->id], 'method' => 'patch']) !!}

                        @include('iot_devices.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/iot_devices/fields.blade.php
<!-- Ipserver Field
<div class="form-group col-sm-6">
    {!! Form::label('ipServer', 'Servidor Fiware:') !!}
    {!! Form::text('ipServer', null, ['class' => 'form-control']) !!}
</div> -->

<!-- Fiwareservice Field
<div class="form-group col-sm-6">
    {!! Form::label('fiwareService', 'Base de datos:') !!}
    {!! Form::text('fiwareService', null, ['class' => 'form-control']) !!}
</div> -->

<!-- Fiwarepath Field -->
<div class="form-group col-sm-6">
    {!! Form::label('fiwarePath', 'Nivel de Datos:') !!}
    {{ Form::select('fiwarePath', $spa, '', ['class' => 'form-control']) }}
</div>

<!-- Device Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('device_id', 'Número del dispositivo:') !!}
    {{ Form::select('device_id', $userId, '', ['class' => 'form-control']) }}
</div>

<!-- Entity Name Field
<div class="form-group col-sm-6">
    {!! Form::label('entity_name', 'Nombre del dispositivo:') !!}
    {!! Form::text('entity_name', null, ['class' => 'form-control']) !!}
</div>-->

<!-- Entity Type Field -->
<div class="form-group col-sm-6">
    {!! Form::label('entity_type', 'Conjunto de datos:') !!}
    {{ Form::select('entity_type', $conjunto, '', ['class' => 'form-control']) }}
</div>

<!--<div class="form-group col-sm-12">
    <p><strong>Parámetros de Sensor</strong></p>
    <button type="button" class="btn btn-primary" id="agregarAttr">Agregar Parámetros</button>
    <div id="attr" class="containerFlexAttr">
    </div>
</div>-->

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Crear', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('iotDevices.index') !!}" class="btn btn-default">Cancelar</a>
</div>

resources/views/iot_devices/index.blade.php
@extends('layouts.app')

@section('content')
<section class="content-header">
        <div class="headerTable">
            <h1 class="pull-left txtH1">Lista</h1>
            <h1 class="pull-right">
                <a class="forma pull-right" style="margin-right:10px" href="{!! route('iotDevices.create') !!}">+</a>
            </h1>
        </div>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('iot_devices.table')
            </div>
        </div>
        <div class="text-center">

        </div>
    </div>
@endsection

resources/views/iot_devices/show.blade.php
<style>
        .content .box{
            width:21.45vw !important;
            margin-left: 32vw;
        }

        .flexInput {
            width: 23vw !important;
            margin-left: 32vw;
            padding-top: 6vw;
        }


        </style>
@extends('layouts.app')

@section('content')
<section class="content-header flexInput">
        <div class="headerInput vCenter">
            <h1>
                Ver
            </h1>
        </div>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body formInput">
                <div class="row" style="padding-left: 20px">
                    @include('iot_devices.show_fields')
                    <a href="{!! route('iotDevices.index') !!}" class="btn btn-primary top">Regresar</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/iot_devices/show_fields.blade.php
<!-- Id Field
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $iotDevice->id !!}</p>
</div>-->

<!-- Ipserver Field -->
<div class="form-group col-sm-6">
    {!! Form::label('ipServer', 'Servidor Fiware:') !!}
    <p>{!! $iotDevice->ipServer !!}</p>
</div>

<!-- Fiwareservice Field -->
<div class="form-group col-sm-6">
    {!! Form::label('fiwareService', 'Base de datos:') !!}
    <p>{!! $iotDevice->fiwareService !!}</p>
</div>

<!-- Fiwarepath Field -->
<div class="form-group col-sm-6">
    {!! Form::label('fiwarePath', 'Nombre de spa:') !!}
    <p>{!! $iotDevice->fiwarePath !!}</p>
</div>

<!-- Device Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('device_id', 'Id Dispositivo:') !!}
    <p>{!! $iotDevice->device_id !!}</p>
</div>

<!-- Entity Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('entity_name', 'Nombre del dispositivo:') !!}
    <p>{!! $iotDevice->entity_name !!}</p>
</div>

<!-- Entity Type Field -->
<div class="form-group col-sm-6">
    {!! Form::label('entity_type', 'Conjunto de datos:') !!}
    <p>{!! $iotDevice->entity_type !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group col-sm-12">
    {!! Form::label('created_at', 'Creación:') !!}
    <p>{!! $iotDevice->created_at !!}</p>
</div>

<!-- Updated At Field
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $iotDevice->updated_at !!}</p>
</div>-->

resources/views/iot_devices/table.blade.php
<div class="table-responsive">
    <table class="table" id="iotDevices-table">
        <thead>
            <tr>
                <th>Servidor Fiware</th>
        <th>Base de datos</th>
        <th>Device Id</th>
        <th>Nombre del sensor</th>
        <th>Conjunto de datos</th>
                <th colspan="3">Acciones</th>
            </tr>
        </thead>
        <tbody>
        @foreach($iotDevices as $iotDevice)
            <tr>
                <td>{!! $iotDevice->ipServer !!}</td>
            <td>{!! $iotDevice->fiwareService !!}</td>
            <td>{!! $iotDevice->device_id !!}</td>
            <td>{!! $iotDevice->entity_name !!}</td>
            <td>{!! $iotDevice->entity_type !!}</td>
                <td class="actions">
                    {!! Form::open(['route' => ['iotDevices.destroy', $iotDevice->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{!! route('iotDevices.show', [$iotDevice->id]) !!}" class='iconoFuente'><i class="glyphicon glyphicon-eye-open"></i></a>
                        <!--<a href="{!! route('iotDevices.edit', [$iotDevice->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>-->
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'iconoFuente', 'onclick' => "return confirm('Seguro que desea borrar el sensor?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>