routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Auth::routes();

Route::get('/home', 'HomeController@index');

Route::resource('notifies', 'notifyController');

Route::resource('entities', 'entityController');

Route::resource('atributes', 'atributeController');

Route::resource('$iotServices', '$iotServiceController');

Route::resource('iotServices', 'iotServiceController');

Route::resource('iotDevices', 'iot_deviceController');

Route::resource('iotDeviceAttributes', 'iot_device_attributeController');

Route::resource('iotDeviceAttributes', 'iot_device_attributeController');

Route::get('fitbits/sync', 'fitbitController@syncup')->name('fitbits.sync');

Route::get('fitbits/sync/sleep', 'fitbitController@syncupSleep')->name('fitbits.syncupSleep');

Route::resource('fitbits', 'fitbitController');

Route::get('temperatura/form', 'fiwareController@form')->name('temperatura.form');

Route::get('temperatura/sensores/{nombre}', 'fiwareController@getSensores');

Route::post('temperatura/consulta', 'fiwareController@consulta')->name('temperatura.consulta');

Route::get('presion/form', 'fiwareController@formPresion')->name('presion.formPresion');

Route::get('presion/sensores/{nombre}', 'fiwareController@getSensoresPresion');

Route::post('presion/consulta', 'fiwareController@consultaPresion')->name('presion.consultaPresion');

Route::get('humedad/form', 'fiwareController@formHumedad')->name('humedad.formHumedad');

Route::get('humedad/sensores/{nombre}', 'fiwareController@getSensoresHumedad');

Route::post('humedad/consulta', 'fiwareController@consultaHumedad')->name('humedad.consultaHumedad');

Route::resource('temperatura', 'fiwareController');

//Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

Route::resource('heartRates', 'heartRateController');

Route::resource('heartInterDays', 'heartInterDayController');

Route::resource('sleeps', 'sleepController');

Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

app/Models/heartInterDay.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class heartInterDay
 * @package App\Models
 * @version November 28, 2019, 2:52 pm UTC
 *
 */
class heartInterDay extends Model
{
    //use SoftDeletes;

    public $table = 'urn_ngsi-Id_Diary_Diary';


    protected $dates = ['deleted_at'];



    public $fillable = [

    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'recvTimeTs'=> 'string',
        'recvTime'=> 'string',
        'fiwareServicePath'=> 'string',
        'entityId'=> 'string',
        'entityType'=> 'string',
        'attrName'=> 'string',
        'attrType'=> 'string',
        'attrValue'=> 'string',
        'attrMd'=> 'string',
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [

    ];


}

app/Http/Controllers/heartInterDayController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateheartInterDayRequest;
use App\Http\Requests\UpdateheartInterDayRequest;
use App\Repositories\heartInterDayRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;
use App\Models\fitbit;
use Carbon\Carbon;
use App\Models\heartInterDay;

class heartInterDayController extends AppBaseController
{
    /** @var  heartInterDayRepository */
    private $heartInterDayRepository;

    public function __construct(heartInterDayRepository $heartInterDayRepo)
    {
        $this->heartInterDayRepository = $heartInterDayRepo;
    }

    /**
     * Display a listing of the heartInterDay.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        //$heartInterDays = $this->heartInterDayRepository->all();
        $fitbitUser = fitbit::pluck('name','user_id');
        $startDate = new Carbon('yesterday');
        $endDate = Carbon::now();
        return view('heart_inter_days.index');
    }

    /**
     * Show the form for creating a new heartInterDay.
     *
     * @return Response
     */
    public function create()
    {
        $fitbitUser = fitbit::pluck('name','user_id');
        $startDate = new Carbon('yesterday');
        $endDate = Carbon::now();
        return view('heart_inter_days.create')->with('fitbitUser', $fitbitUser)->with('endDate', $endDate)->with('startDate', $startDate);
    }

    /**
     * Store a newly created heartInterDay in storage.
     *
     * @param CreateheartInterDayRequest $request
     *
     * @return Response
     */
    public function store(CreateheartInterDayRequest $request)
    {
        $input = $request->all();

        $dateStart = $input['dateStart']."T00:00:00.000";
        $dateEnd = $input['dateStart']."T23:59:59.000";
        $rango = "24 horas de consulta de ritmo cardíaco ";
        $datos = heartInterDay::where('attrValue','=',$input['user_id'])->whereBetween('recvTime', array($dateStart, $dateEnd ))->get('recvTime')->toArray();

        foreach($datos as $dato){
            $datosV['time'][] = heartInterDay::where('recvTime', '=', $dato['recvTime'] )->where('attrName', '=', 'time')->get('attrValue')->toArray();
            $datosV['value'][] = heartInterDay::where('recvTime', '=', $dato['recvTime'] )->where('attrName', '=', 'value')->get('attrValue')->toArray();

        }

        $rango = $input['dateStart'];
        $total = count($datosV['time']);

        for($i=0; $i<$total; $i++){
            $dataV[$i]['x'] = $datosV['time'][$i][0]['attrValue'];
            $dataV[$i]['y'] = $datosV['value'][$i][0]['attrValue'];
        }
        return view('heart_inter_days.chart')->with('datos', $dataV)->with('rango', $rango);

    }

    /**
     * Display the specified heartInterDay.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $heartInterDay = $this->heartInterDayRepository->find($id);

        if (empty($heartInterDay)) {
            Flash::error('Heart Inter Day not found');

            return redirect(route('heartInterDays.index'));
        }

        return view('heart_inter_days.show')->with('heartInterDay', $heartInterDay);
    }

    /**
     * Show the form for editing the specified heartInterDay.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $heartInterDay = $this->heartInterDayRepository->find($id);

        if (empty($heartInterDay)) {
            Flash::error('Heart Inter Day not found');

            return redirect(route('heartInterDays.index'));
        }

        return view('heart_inter_days.edit')->with('heartInterDay', $heartInterDay);
    }

    /**
     * Update the specified heartInterDay in storage.
     *
     * @param int $id
     * @param UpdateheartInterDayRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateheartInterDayRequest $request)
    {
        $heartInterDay = $this->heartInterDayRepository->find($id);

        if (empty($heartInterDay)) {
            Flash::error('Heart Inter Day not found');

            return redirect(route('heartInterDays.index'));
        }

        $heartInterDay = $this->heartInterDayRepository->update($request->all(), $id);

        Flash::success('Heart Inter Day updated successfully.');

        return redirect(route('heartInterDays.index'));
    }

    /**
     * Remove the specified heartInterDay from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $heartInterDay = $this->heartInterDayRepository->find($id);

        if (empty($heartInterDay)) {
            Flash::error('Heart Inter Day not found');

            return redirect(route('heartInterDays.index'));
        }

        $this->heartInterDayRepository->delete($id);

        Flash::success('Heart Inter Day deleted successfully.');

        return redirect(route('heartInterDays.index'));
    }
}

resources/views/heart_inter_days/chart.blade.php
@extends('layouts.app')
@php
$total = count($datos);
@endphp

@section('content')
    <section class="content-header flexInputChart">
            <div class="headerInput vCenter">
                    <h1>Lectura de ritmo cardíaco</h1>

                    <p class="txtHeaderFecha">Fecha: {{$rango}}</p>
                </div>

    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">


            <div class="box-body">
                <div class="row formInputChart">
                    <html>
    <style>
        .headerInput {
            background-color: #3d4f7c;
            height: 8vh;
            color: white;
            font-size: 9px !important;
            padding-left: 10px;
        }
        .txtHeaderFecha{
            font-size:14px;
        }
    </style>
  <head>
    <!--Load the AJAX API-->
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">

      // Load the Visualization API and the corechart package.
      google.charts.load('current', {'packages':['corechart']});

      // Set a callback to run when the Google Visualization API is loaded.
      google.charts.setOnLoadCallback(drawChart);

      // Callback that creates and populates a data table,
      // instantiates the pie chart, passes in the data and
      // draws it.
      function drawChart() {
        var ventana_ancho = $(window).width() - 550;
        var ventana_alto = $(window).height() - 400;
        if(ventana_ancho > 834 && ventana_ancho < 1599){
            ventana_ancho = 800;
        }



        // Create the data table.
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Calorías');
        data.addColumn('number', 'Tiempo');
        data.addRows([
            @for($i=0; $i<$total; $i++)
                ['{{ $datos[$i]['x'] }}' , {{ $datos[$i]['y'] }}],
            @endfor
        ]);
        // Set chart option
        var options = {
                       'width':ventana_ancho,
                       'height':ventana_alto,
                       chartArea: {height: '95%'}

                    };

        // Instantiate and draw our chart, passing in some options.
        var chart = new google.visualization.ColumnChart(document.getElementById('chart_div'));
        chart.draw(data, options);
      }
    </script>
  </head>

  <body>


        <div id="chart_div"></div>

  </body>
</html>
                </div>
            </div>
        </div>
    </div>
@endsection
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script>
        $(document).ready(function($){
        $(window).resize(function(){
            var ventana_ancho = $(window).width();
            var ventana_alto = $(window).height();
            drawChart();
        })
      });
    </script>

resources/views/heart_inter_days/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header flexInput">
            <div class="headerInput vCenter">

                    <h1>Zonas de Consulta</h1>
                </div>

    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row formInput">
                    {!! Form::open(['route' => 'heartInterDays.store']) !!}

                        @include('heart_inter_days.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/heart_inter_days/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Heart Inter Day
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($heartInterDay, ['route' => ['heartInterDays.update', $heartInterDay->id], 'method' => 'patch']) !!}

                        @include('heart_inter_days.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/heart_inter_days/fields.blade.php
<!-- fecha inicio Field -->
<div class="form-group col-sm-12">
        {!! Form::label('dateStart', 'Fecha Comienzo:') !!}
        {{ Form::date('dateStart', $startDate ) }}

    </div>

    <!-- fecha fin Field
    <div class="form-group col-sm-6">
        {!! Form::label('dateEnd', 'Fecha Fin:') !!}
        {{ Form::date('dateEnd', $endDate) }}

    </div>-->

    <!--  Local Field -->
    <div class="form-group col-sm-12">
        {!! Form::label('user_id', 'Usuario:') !!}
        {{ Form::select('user_id', $fitbitUser, ['class' => 'form-control']) }}
    </div>

    <!-- Submit Field -->
    <div class="form-group col-sm-12">
        {!! Form::submit('Consultar', ['class' => 'btn btn-primary']) !!}
    </div>

resources/views/heart_inter_days/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Heart Inter Days</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('heartInterDays.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('heart_inter_days.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/heart_inter_days/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Heart Inter Day
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('heart_inter_days.show_fields')
                    <a href="{!! route('heartInterDays.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/heart_inter_days/show_fields.blade.php
<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $heartInterDay->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $heartInterDay->updated_at !!}</p>
</div>

resources/views/heart_inter_days/table.blade.php
<div class="table-responsive">
    <table class="table" id="heartInterDays-table">
        <thead>
            <tr>
                
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($heartInterDays as $heartInterDay)
            <tr>
                
                <td>
                    {!! Form::open(['route' => ['heartInterDays.destroy', $heartInterDay->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{!! route('heartInterDays.show', [$heartInterDay->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                        <a href="{!! route('heartInterDays.edit', [$heartInterDay->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>