routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Auth::routes();

Route::get('/home', 'HomeController@index');

Route::resource('notifies', 'notifyController');

Route::resource('entities', 'entityController');

Route::resource('atributes', 'atributeController');

Route::resource('$iotServices', '$iotServiceController');

Route::resource('iotServices', 'iotServiceController');

Route::resource('iotDevices', 'iot_deviceController');

Route::resource('iotDeviceAttributes', 'iot_device_attributeController');

Route::resource('iotDeviceAttributes', 'iot_device_attributeController');

Route::get('fitbits/sync', 'fitbitController@syncup')->name('fitbits.sync');

Route::get('fitbits/sync/sleep', 'fitbitController@syncupSleep')->name('fitbits.syncupSleep');

Route::resource('fitbits', 'fitbitController');

Route::get('temperatura/form', 'fiwareController@form')->name('temperatura.form');

Route::get('temperatura/sensores/{nombre}', 'fiwareController@getSensores');

Route::post('temperatura/consulta', 'fiwareController@consulta')->name('temperatura.consulta');

Route::get('presion/form', 'fiwareController@formPresion')->name('presion.formPresion');

Route::get('presion/sensores/{nombre}', 'fiwareController@getSensoresPresion');

Route::post('presion/consulta', 'fiwareController@consultaPresion')->name('presion.consultaPresion');

Route::get('humedad/form', 'fiwareController@formHumedad')->name('humedad.formHumedad');

Route::get('humedad/sensores/{nombre}', 'fiwareController@getSensoresHumedad');

Route::post('humedad/consulta', 'fiwareController@consultaHumedad')->name('humedad.consultaHumedad');

Route::resource('temperatura', 'fiwareController');

//Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

Route::resource('heartRates', 'heartRateController');

Route::resource('heartInterDays', 'heartInterDayController');

Route::resource('sleeps', 'sleepController');

Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

app/Models/iot_device_attribute.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class iot_device_attribute
 * @package App\Models
 * @version June 2, 2019, 2:41 pm UTC
 *
 * @property string name
 * @property string type
 * @property integer deviceAttr_id
 */
class iot_device_attribute extends Model
{
    use SoftDeletes;

    public $table = 'iot_device_attributes';


    protected $dates = ['deleted_at'];


    public $fillable = [
        'name',
        'type',
        'objective',
        'attr_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'name' => 'string',
        'type' => 'string',
        'objective' => 'string',
        'attr_id' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [];

    public function iotservice()

    {

        return $this->belongsTo('App\Models\iot_device');

    }




}

app/Http/Controllers/iot_device_attributeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Createiot_device_attributeRequest;
use App\Http\Requests\Updateiot_device_attributeRequest;
use App\Repositories\iot_device_attributeRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class iot_device_attributeController extends AppBaseController
{
    /** @var  iot_device_attributeRepository */
    private $iotDeviceAttributeRepository;

    public function __construct(iot_device_attributeRepository $iotDeviceAttributeRepo)
    {
        $this->iotDeviceAttributeRepository = $iotDeviceAttributeRepo;
    }

    /**
     * Display a listing of the iot_device_attribute.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $iotDeviceAttributes = $this->iotDeviceAttributeRepository->all();

        return view('iot_device_attributes.index')
            ->with('iotDeviceAttributes', $iotDeviceAttributes);
    }

    /**
     * Show the form for creating a new iot_device_attribute.
     *
     * @return Response
     */
    public function create()
    {
        return view('iot_device_attributes.create');
    }

    /**
     * Store a newly created iot_device_attribute in storage.
     *
     * @param Createiot_device_attributeRequest $request
     *
     * @return Response
     */
    public function store(Createiot_device_attributeRequest $request)
    {
        $input = $request->all();

        $iotDeviceAttribute = $this->iotDeviceAttributeRepository->create($input);

        Flash::success('Iot Device Attribute saved successfully.');

        return redirect(route('iotDeviceAttributes.index'));
    }

    /**
     * Display the specified iot_device_attribute.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $iotDeviceAttribute = $this->iotDeviceAttributeRepository->find($id);

        if (empty($iotDeviceAttribute)) {
            Flash::error('Iot Device Attribute not found');

            return redirect(route('iotDeviceAttributes.index'));
        }

        return view('iot_device_attributes.show')->with('iotDeviceAttribute', $iotDeviceAttribute);
    }

    /**
     * Show the form for editing the specified iot_device_attribute.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $iotDeviceAttribute = $this->iotDeviceAttributeRepository->find($id);

        if (empty($iotDeviceAttribute)) {
            Flash::error('Iot Device Attribute not found');

            return redirect(route('iotDeviceAttributes.index'));
        }

        return view('iot_device_attributes.edit')->with('iotDeviceAttribute', $iotDeviceAttribute);
    }

    /**
     * Update the specified iot_device_attribute in storage.
     *
     * @param int $id
     * @param Updateiot_device_attributeRequest $request
     *
     * @return Response
     */
    public function update($id, Updateiot_device_attributeRequest $request)
    {
        $iotDeviceAttribute = $this->iotDeviceAttributeRepository->find($id);

        if (empty($iotDeviceAttribute)) {
            Flash::error('Iot Device Attribute not found');

            return redirect(route('iotDeviceAttributes.index'));
        }

        $iotDeviceAttribute = $this->iotDeviceAttributeRepository->update($request->all(), $id);

        Flash::success('Iot Device Attribute updated successfully.');

        return redirect(route('iotDeviceAttributes.index'));
    }

    /**
     * Remove the specified iot_device_attribute from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $iotDeviceAttribute = $this->iotDeviceAttributeRepository->find($id);

        if (empty($iotDeviceAttribute)) {
            Flash::error('Iot Device Attribute not found');

            return redirect(route('iotDeviceAttributes.index'));
        }

        $this->iotDeviceAttributeRepository->delete($id);

        Flash::success('Iot Device Attribute deleted successfully.');

        return redirect(route('iotDeviceAttributes.index'));
    }
}

resources/views/iot_device_attributes/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Iot Device Attribute
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'iotDeviceAttributes.store']) !!}

                        @include('iot_device_attributes.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/iot_device_attributes/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Iot Device Attribute
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($iotDeviceAttribute, ['route' => ['iotDeviceAttributes.update', $iotDeviceAttribute->id], 'method' => 'patch']) !!}

                        @include('iot_device_attributes.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/iot_device_attributes/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Type Field -->
<div class="form-group col-sm-6">
    {!! Form::label('type', 'Type:') !!}
    {!! Form::text('type', null, ['class' => 'form-control']) !!}
</div>

<!-- Entity Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('entity_id', 'Entity Id:') !!}
    {!! Form::text('entity_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('iotDeviceAttributes.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/iot_device_attributes/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Iot Device Attributes</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('iotDeviceAttributes.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('iot_device_attributes.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/iot_device_attributes/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Iot Device Attribute
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('iot_device_attributes.show_fields')
                    <a href="{!! route('iotDeviceAttributes.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/iot_device_attributes/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $iotDeviceAttribute->id !!}</p>
</div>

<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{!! $iotDeviceAttribute->name !!}</p>
</div>

<!-- Type Field -->
<div class="form-group">
    {!! Form::label('type', 'Type:') !!}
    <p>{!! $iotDeviceAttribute->type !!}</p>
</div>

<!-- Entity Id Field -->
<div class="form-group">
    {!! Form::label('entity_id', 'Entity Id:') !!}
    <p>{!! $iotDeviceAttribute->entity_id !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $iotDeviceAttribute->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $iotDeviceAttribute->updated_at !!}</p>
</div>

resources/views/iot_device_attributes/table.blade.php
<div class="table-responsive">
    <table class="table" id="iotDeviceAttributes-table">
        <thead>
            <tr>
                <th>Name</th>
        <th>Type</th>
        <th>Entity Id</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($iotDeviceAttributes as $iotDeviceAttribute)
            <tr>
                <td>{!! $iotDeviceAttribute->name !!}</td>
            <td>{!! $iotDeviceAttribute->type !!}</td>
            <td>{!! $iotDeviceAttribute->entity_id !!}</td>
                <td>
                    {!! Form::open(['route' => ['iotDeviceAttributes.destroy', $iotDeviceAttribute->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{!! route('iotDeviceAttributes.show', [$iotDeviceAttribute->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                        <a href="{!! route('iotDeviceAttributes.edit', [$iotDeviceAttribute->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>